# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Copy project files
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install dependencies and build (package.json/package-lock.json are the
# single source of truth for dependencies - no build-time patching)
RUN npm ci --ignore-scripts && npm run build

# Default command: stdio server
CMD ["node", "build/index.js"]
