# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Copy project files
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Fix dependency version mismatch
RUN sed -i 's/"@modelcontextprotocol\/sdk":.*$/"@modelcontextprotocol\/sdk": "^1.8.0",/' package.json

# Install dependencies and build
RUN npm install --ignore-scripts && npm run build

# Default command: stdio server
CMD ["node", "build/index.js"]
